### ISSUE TITLE
Fix failing Paths tests and pipeline

### ISSUE THREAD

**Issue by gokhanercan** [gokhanercan/gen-atomic#12]
Probably it is failing on Mac and Linux. We are supposed to implement it to be OS agnostic.  @osman-serhat-yilmaz 
This will probably fix the pipeline error. 
See the part with: 
_=============== 3 failed, 7 passed, 1 warning, 1 error in 5.74s ================_

**Comment by osman-serhat-yilmaz** [comment]
Paths.py updated, now it is OS agnostic. GitHub Actions pytest operation doesn't give errors for paths anymore.

**Comment by gokhanercan** [comment]
I will fix the pipeline errors
