### ISSUE TITLE
Eval by Precision/Recall/F1

### ISSUE THREAD

**Issue by gokhanercan** [gokhanercan/gen-atomic#16]
Metrics added to ExperimentHost.py, [related commit](https://github.com/gokhanercan/gen-atomic/commit/789955b0ba8a9dc9d2897142420b70c8932c9c0d)

**Comment by gokhanercan** [comment]
I disabled news metrics to have the pipeline green again. 
I was getting divide-by-zero error on integration tests. 
We also need to add new metrics to default reporting. 

https://github.com/gokhanercan/gen-atomic/actions/runs/9150598274/job/25155562822
`    precision: float = (float(ccPassed) / float(ccPassed + (icCount - icPassed))) * 100
E           
ZeroDivisionError: float division by zero`

**Comment by osman-serhat-yilmaz** [comment]
https://github.com/gokhanercan/gen-atomic/commit/c9c59fcc9ca64cd820d91520dc7a2c0e0b1c7b20

added precision recall and f1 using scikit-learn
